// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SRT.ServiceAPI.Context;

#nullable disable

namespace SRT.ServiceAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240123142456_MigrationSrt")]
    partial class MigrationSrt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SRT.ServiceAPI.Models.Cotacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_coleta");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_entrega_lim");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_cad");

                    b.Property<string>("DestBairro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("de_dest_bairro");

                    b.Property<string>("DestCEP")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("de_dest_cep");

                    b.Property<string>("DestCNPJorCPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("de_dest_cnpj_cpf");

                    b.Property<string>("DestCelular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("de_dest_celular");

                    b.Property<string>("DestCidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("de_dest_cidade");

                    b.Property<string>("DestEndereco")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("de_dest_endereco");

                    b.Property<string>("DestNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("de_dest_nome");

                    b.Property<string>("DestResponsavel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("de_dest_responsavel");

                    b.Property<string>("DestTelefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("de_dest_telefone");

                    b.Property<string>("DestUF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("de_dest_uf");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("si_login_cad");

                    b.Property<string>("NPedido")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("de_num_pedido");

                    b.Property<string>("PagadorFrete")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("de_pagador_frete");

                    b.Property<string>("RemBairro")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("de_remet_bairro");

                    b.Property<string>("RemCEP")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("de_remet_cep");

                    b.Property<string>("RemCNPJorCPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("de_remet_cpnj_cpf");

                    b.Property<string>("RemCelular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("de_remet_celular");

                    b.Property<string>("RemCidade")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("de_remet_cidade");

                    b.Property<string>("RemEndereco")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("de_remet_endereco");

                    b.Property<string>("RemNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("de_remet_nome");

                    b.Property<string>("RemResponsavel")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("de_remet_responsavel");

                    b.Property<string>("RemTelefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("de_remet_telefone");

                    b.Property<string>("RemUF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("de_remet_uf");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("de_status");

                    b.Property<string>("TipoFrete")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("de_tpfrete");

                    b.Property<string>("Urgencia")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("de_urgencia");

                    b.Property<string>("ValorNF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("de_valor_nf");

                    b.HasKey("Id");

                    b.ToTable("tsrtcotacao");
                });
#pragma warning restore 612, 618
        }
    }
}
